// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/records_v1/records.proto

package records_v1

import (
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"
    timestamppb "google.golang.org/protobuf/types/known/timestamppb"
    reflect "reflect"
    sync "sync"
    unsafe "unsafe"
)

const (
    // Verify that this generated code is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
    // Verify that runtime/protoimpl is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    RecordId      uint64                 `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
    *x = GetRequest{}
    mi := &file_api_records_v1_records_proto_msgTypes[0]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[0]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetRecordId() uint64 {
    if x != nil {
        return x.RecordId
    }
    return 0
}

type GetResponse struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
    *x = GetResponse{}
    mi := &file_api_records_v1_records_proto_msgTypes[1]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[1]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetRecord() *Record {
    if x != nil {
        return x.Record
    }
    return nil
}

type ListRequest struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
    Type          *uint32                `protobuf:"varint,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
    *x = ListRequest{}
    mi := &file_api_records_v1_records_proto_msgTypes[2]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[2]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetLogin() string {
    if x != nil {
        return x.Login
    }
    return ""
}

func (x *ListRequest) GetType() uint32 {
    if x != nil && x.Type != nil {
        return *x.Type
    }
    return 0
}

type ListResponse struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
    *x = ListResponse{}
    mi := &file_api_records_v1_records_proto_msgTypes[3]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[3]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetRecord() *Record {
    if x != nil {
        return x.Record
    }
    return nil
}

type Record struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
    Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
    Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
    Credentials   []*Credential          `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty"`
    Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
    *x = Record{}
    mi := &file_api_records_v1_records_proto_msgTypes[4]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[4]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() uint64 {
    if x != nil {
        return x.Id
    }
    return 0
}

func (x *Record) GetType() uint32 {
    if x != nil {
        return x.Type
    }
    return 0
}

func (x *Record) GetAddress() string {
    if x != nil {
        return x.Address
    }
    return ""
}

func (x *Record) GetCredentials() []*Credential {
    if x != nil {
        return x.Credentials
    }
    return nil
}

func (x *Record) GetComment() string {
    if x != nil {
        return x.Comment
    }
    return ""
}

type Credential struct {
    state         protoimpl.MessageState `protogen:"open.v1"`
    Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
    Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
    CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
    Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
    unknownFields protoimpl.UnknownFields
    sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
    *x = Credential{}
    mi := &file_api_records_v1_records_proto_msgTypes[5]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
    mi := &file_api_records_v1_records_proto_msgTypes[5]
    if x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
    return file_api_records_v1_records_proto_rawDescGZIP(), []int{5}
}

func (x *Credential) GetLogin() string {
    if x != nil {
        return x.Login
    }
    return ""
}

func (x *Credential) GetPassword() string {
    if x != nil {
        return x.Password
    }
    return ""
}

func (x *Credential) GetCreatedAt() *timestamppb.Timestamp {
    if x != nil {
        return x.CreatedAt
    }
    return nil
}

func (x *Credential) GetComment() string {
    if x != nil {
        return x.Comment
    }
    return ""
}

var File_api_records_v1_records_proto protoreflect.FileDescriptor

var file_api_records_v1_records_proto_rawDesc = string([]byte{
    0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31,
    0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
    0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
    0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
    0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0a, 0x47,
    0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63,
    0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65,
    0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
    0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18,
    0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f,
    0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72,
    0x64, 0x22, 0x45, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
    0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
    0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
    0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42,
    0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
    0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f,
    0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
    0x64, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65,
    0x63, 0x6f, 0x72, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
    0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
    0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
    0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
    0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a,
    0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03,
    0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x2e,
    0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64,
    0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
    0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
    0x74, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
    0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
    0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
    0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
    0x72, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
    0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
    0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
    0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a,
    0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
    0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x80, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f,
    0x72, 0x64, 0x73, 0x56, 0x31, 0x12, 0x36, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x72,
    0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
    0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76,
    0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
    0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f,
    0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
    0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
    0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x6b,
    0x67, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x63,
    0x6f, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
    file_api_records_v1_records_proto_rawDescOnce sync.Once
    file_api_records_v1_records_proto_rawDescData []byte
)

func file_api_records_v1_records_proto_rawDescGZIP() []byte {
    file_api_records_v1_records_proto_rawDescOnce.Do(func() {
        file_api_records_v1_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_records_v1_records_proto_rawDesc), len(file_api_records_v1_records_proto_rawDesc)))
    })
    return file_api_records_v1_records_proto_rawDescData
}

var file_api_records_v1_records_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_records_v1_records_proto_goTypes = []any{
    (*GetRequest)(nil),            // 0: records_v1.GetRequest
    (*GetResponse)(nil),           // 1: records_v1.GetResponse
    (*ListRequest)(nil),           // 2: records_v1.ListRequest
    (*ListResponse)(nil),          // 3: records_v1.ListResponse
    (*Record)(nil),                // 4: records_v1.Record
    (*Credential)(nil),            // 5: records_v1.Credential
    (*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_records_v1_records_proto_depIdxs = []int32{
    4, // 0: records_v1.GetResponse.record:type_name -> records_v1.Record
    4, // 1: records_v1.ListResponse.record:type_name -> records_v1.Record
    5, // 2: records_v1.Record.credentials:type_name -> records_v1.Credential
    6, // 3: records_v1.Credential.created_at:type_name -> google.protobuf.Timestamp
    0, // 4: records_v1.RecordsV1.Get:input_type -> records_v1.GetRequest
    2, // 5: records_v1.RecordsV1.List:input_type -> records_v1.ListRequest
    1, // 6: records_v1.RecordsV1.Get:output_type -> records_v1.GetResponse
    3, // 7: records_v1.RecordsV1.List:output_type -> records_v1.ListResponse
    6, // [6:8] is the sub-list for method output_type
    4, // [4:6] is the sub-list for method input_type
    4, // [4:4] is the sub-list for extension type_name
    4, // [4:4] is the sub-list for extension extendee
    0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_records_v1_records_proto_init() }
func file_api_records_v1_records_proto_init() {
    if File_api_records_v1_records_proto != nil {
        return
    }
    file_api_records_v1_records_proto_msgTypes[2].OneofWrappers = []any{}
    type x struct{}
    out := protoimpl.TypeBuilder{
        File: protoimpl.DescBuilder{
            GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
            RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_records_v1_records_proto_rawDesc), len(file_api_records_v1_records_proto_rawDesc)),
            NumEnums:      0,
            NumMessages:   6,
            NumExtensions: 0,
            NumServices:   1,
        },
        GoTypes:           file_api_records_v1_records_proto_goTypes,
        DependencyIndexes: file_api_records_v1_records_proto_depIdxs,
        MessageInfos:      file_api_records_v1_records_proto_msgTypes,
    }.Build()
    File_api_records_v1_records_proto = out.File
    file_api_records_v1_records_proto_goTypes = nil
    file_api_records_v1_records_proto_depIdxs = nil
}
