// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: keyper/v1/secret.proto

package keyper

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretType contains a list of secrets types.
type SecretType int32

const (
	// SECRET_TYPE_UNSPECIFIED is a default secret type.
	SecretType_SECRET_TYPE_UNSPECIFIED SecretType = 0
	// SECRET_TYPE_CREDENTIALS specifies a secret with user credentials as data.
	SecretType_SECRET_TYPE_CREDENTIALS SecretType = 1
	// SECRET_TYPE_TEXT specifies a secret with arbitrary text as data.
	SecretType_SECRET_TYPE_TEXT SecretType = 2
	// SECRET_TYPE_BINARY specifies a secret with binary data.
	SecretType_SECRET_TYPE_BINARY SecretType = 3
	// SECRET_TYPE_TEXT specifies a secret with bank card as data.
	SecretType_SECRET_TYPE_CARD SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_CREDENTIALS",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED": 0,
		"SECRET_TYPE_CREDENTIALS": 1,
		"SECRET_TYPE_TEXT":        2,
		"SECRET_TYPE_BINARY":      3,
		"SECRET_TYPE_CARD":        4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_keyper_v1_secret_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_keyper_v1_secret_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{0}
}

// Secret contains secrets info, metadata and data.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets identifier (uuid).
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Secrets name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Secrets type.
	Type SecretType `protobuf:"varint,3,opt,name=type,proto3,enum=keyper.v1.SecretType" json:"type,omitempty"`
	// Secrets metadata.
	Metadata []byte `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Secrets data.
	Data [][]byte `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	// Secrets arbitrary description or comment.
	Comment *string `protobuf:"bytes,6,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	// Secrets creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	// Secrets modification time.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_keyper_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Secret) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Secret) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSecretV1Request contains a new secret to store in the service.
type CreateSecretV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A secret to store.
	Secret        *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretV1Request) Reset() {
	*x = CreateSecretV1Request{}
	mi := &file_keyper_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretV1Request) ProtoMessage() {}

func (x *CreateSecretV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretV1Request.ProtoReflect.Descriptor instead.
func (*CreateSecretV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretV1Request) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// CreateSecretV1Response is received in response to a CreateSecretV1 rpc.
//
// It contains a result of secret creation - secrets identifier or creation error.
type CreateSecretV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of secret creation.
	Result        *CreateSecretV1Response_CreateSecretResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretV1Response) Reset() {
	*x = CreateSecretV1Response{}
	mi := &file_keyper_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretV1Response) ProtoMessage() {}

func (x *CreateSecretV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretV1Response.ProtoReflect.Descriptor instead.
func (*CreateSecretV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretV1Response) GetResult() *CreateSecretV1Response_CreateSecretResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetSecretV1Request contains an identifier of a secret to return.
type GetSecretV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets identifier (uuid).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretV1Request) Reset() {
	*x = GetSecretV1Request{}
	mi := &file_keyper_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretV1Request) ProtoMessage() {}

func (x *GetSecretV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretV1Request.ProtoReflect.Descriptor instead.
func (*GetSecretV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretV1Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSecretV1Response is received in response to a GetSecretV1 rpc.
//
// It contains a secret with identifier from request or an error.
type GetSecretV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets search result.
	Result        *GetSecretV1Response_GetSecretResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretV1Response) Reset() {
	*x = GetSecretV1Response{}
	mi := &file_keyper_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretV1Response) ProtoMessage() {}

func (x *GetSecretV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretV1Response.ProtoReflect.Descriptor instead.
func (*GetSecretV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretV1Response) GetResult() *GetSecretV1Response_GetSecretResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// ListSecretsV1Response is received in response to a ListSecretsV1 rpc.
//
// It contains a list of found secrets.
type ListSecretsV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of secrets.
	Secret        []*Secret `protobuf:"bytes,1,rep,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsV1Response) Reset() {
	*x = ListSecretsV1Response{}
	mi := &file_keyper_v1_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsV1Response) ProtoMessage() {}

func (x *ListSecretsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsV1Response.ProtoReflect.Descriptor instead.
func (*ListSecretsV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{5}
}

func (x *ListSecretsV1Response) GetSecret() []*Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// UpdateSecretV1Request contains a secrets data to update in the service storage.
type UpdateSecretV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret with data to update.
	Secret        *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretV1Request) Reset() {
	*x = UpdateSecretV1Request{}
	mi := &file_keyper_v1_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretV1Request) ProtoMessage() {}

func (x *UpdateSecretV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretV1Request.ProtoReflect.Descriptor instead.
func (*UpdateSecretV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSecretV1Request) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// UpdateSecretV1Response is received in response to a UpdateSecretV1 rpc.
//
// It contains a secrets update result.
type UpdateSecretV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets update result.
	Result        *UpdateSecretV1Response_UpdateSecretResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretV1Response) Reset() {
	*x = UpdateSecretV1Response{}
	mi := &file_keyper_v1_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretV1Response) ProtoMessage() {}

func (x *UpdateSecretV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretV1Response.ProtoReflect.Descriptor instead.
func (*UpdateSecretV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSecretV1Response) GetResult() *UpdateSecretV1Response_UpdateSecretResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// DeleteSecretV1Request contains an identifier of the secret to delete from the service storage.
type DeleteSecretV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets identifier (uuid).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretV1Request) Reset() {
	*x = DeleteSecretV1Request{}
	mi := &file_keyper_v1_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretV1Request) ProtoMessage() {}

func (x *DeleteSecretV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretV1Request.ProtoReflect.Descriptor instead.
func (*DeleteSecretV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSecretV1Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSecretV1Response is received in response to a DeleteSecretV1 rpc.
//
// It contains a secrets delete result.
type DeleteSecretV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets deletion result.
	Result        *DeleteSecretV1Response_DeleteSecretResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretV1Response) Reset() {
	*x = DeleteSecretV1Response{}
	mi := &file_keyper_v1_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretV1Response) ProtoMessage() {}

func (x *DeleteSecretV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretV1Response.ProtoReflect.Descriptor instead.
func (*DeleteSecretV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSecretV1Response) GetResult() *DeleteSecretV1Response_DeleteSecretResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// CreateSecretResult contains a result of secrets creation.
type CreateSecretV1Response_CreateSecretResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secrets identifier (uuid).
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Creation error description.
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretV1Response_CreateSecretResult) Reset() {
	*x = CreateSecretV1Response_CreateSecretResult{}
	mi := &file_keyper_v1_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretV1Response_CreateSecretResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretV1Response_CreateSecretResult) ProtoMessage() {}

func (x *CreateSecretV1Response_CreateSecretResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretV1Response_CreateSecretResult.ProtoReflect.Descriptor instead.
func (*CreateSecretV1Response_CreateSecretResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateSecretV1Response_CreateSecretResult) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CreateSecretV1Response_CreateSecretResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// CreateSecretResult contains a result of secrets search.
type GetSecretV1Response_GetSecretResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret with identifier from request.
	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	// Error description.
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretV1Response_GetSecretResult) Reset() {
	*x = GetSecretV1Response_GetSecretResult{}
	mi := &file_keyper_v1_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretV1Response_GetSecretResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretV1Response_GetSecretResult) ProtoMessage() {}

func (x *GetSecretV1Response_GetSecretResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretV1Response_GetSecretResult.ProtoReflect.Descriptor instead.
func (*GetSecretV1Response_GetSecretResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetSecretV1Response_GetSecretResult) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *GetSecretV1Response_GetSecretResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Secret update result.
type UpdateSecretV1Response_UpdateSecretResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update error description.
	Error         *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretV1Response_UpdateSecretResult) Reset() {
	*x = UpdateSecretV1Response_UpdateSecretResult{}
	mi := &file_keyper_v1_secret_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretV1Response_UpdateSecretResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretV1Response_UpdateSecretResult) ProtoMessage() {}

func (x *UpdateSecretV1Response_UpdateSecretResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretV1Response_UpdateSecretResult.ProtoReflect.Descriptor instead.
func (*UpdateSecretV1Response_UpdateSecretResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateSecretV1Response_UpdateSecretResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Secret delete result.
type DeleteSecretV1Response_DeleteSecretResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delete error description.
	Error         *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretV1Response_DeleteSecretResult) Reset() {
	*x = DeleteSecretV1Response_DeleteSecretResult{}
	mi := &file_keyper_v1_secret_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretV1Response_DeleteSecretResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretV1Response_DeleteSecretResult) ProtoMessage() {}

func (x *DeleteSecretV1Response_DeleteSecretResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_secret_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretV1Response_DeleteSecretResult.ProtoReflect.Descriptor instead.
func (*DeleteSecretV1Response_DeleteSecretResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_secret_proto_rawDescGZIP(), []int{9, 0}
}

func (x *DeleteSecretV1Response_DeleteSecretResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_keyper_v1_secret_proto protoreflect.FileDescriptor

const file_keyper_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x16keyper/v1/secret.proto\x12\tkeyper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x92\x03\n" +
	"\x06Secret\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x88\x01\x01\x12 \n" +
	"\x04name\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\x04name\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.keyper.v1.SecretTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12&\n" +
	"\bmetadata\x18\x04 \x01(\fB\n" +
	"\xbaH\a\xc8\x01\x01z\x02\x10\x01R\bmetadata\x12\x1c\n" +
	"\x04data\x18\x05 \x03(\fB\b\xbaH\x05\x92\x01\x02\b\x01R\x04data\x12\x1d\n" +
	"\acomment\x18\x06 \x01(\tH\x01R\acomment\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tcreatedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tupdatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_commentB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"J\n" +
	"\x15CreateSecretV1Request\x121\n" +
	"\x06secret\x18\x01 \x01(\v2\x11.keyper.v1.SecretB\x06\xbaH\x03\xc8\x01\x01R\x06secret\"\xcf\x01\n" +
	"\x16CreateSecretV1Response\x12T\n" +
	"\x06result\x18\x01 \x01(\v24.keyper.v1.CreateSecretV1Response.CreateSecretResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x1a_\n" +
	"\x12CreateSecretResult\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_error\"1\n" +
	"\x12GetSecretV1Request\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"\xd8\x01\n" +
	"\x13GetSecretV1Response\x12N\n" +
	"\x06result\x18\x01 \x01(\v2..keyper.v1.GetSecretV1Response.GetSecretResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x1aq\n" +
	"\x0fGetSecretResult\x12.\n" +
	"\x06secret\x18\x01 \x01(\v2\x11.keyper.v1.SecretH\x00R\x06secret\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01B\t\n" +
	"\a_secretB\b\n" +
	"\x06_error\"B\n" +
	"\x15ListSecretsV1Response\x12)\n" +
	"\x06secret\x18\x01 \x03(\v2\x11.keyper.v1.SecretR\x06secret\"J\n" +
	"\x15UpdateSecretV1Request\x121\n" +
	"\x06secret\x18\x01 \x01(\v2\x11.keyper.v1.SecretB\x06\xbaH\x03\xc8\x01\x01R\x06secret\"\xa9\x01\n" +
	"\x16UpdateSecretV1Response\x12T\n" +
	"\x06result\x18\x01 \x01(\v24.keyper.v1.UpdateSecretV1Response.UpdateSecretResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x1a9\n" +
	"\x12UpdateSecretResult\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"4\n" +
	"\x15DeleteSecretV1Request\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"\xa9\x01\n" +
	"\x16DeleteSecretV1Response\x12T\n" +
	"\x06result\x18\x01 \x01(\v24.keyper.v1.DeleteSecretV1Response.DeleteSecretResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\x1a9\n" +
	"\x12DeleteSecretResult\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*\x8a\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SECRET_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x04B\x97\x01\n" +
	"\rcom.keyper.v1B\vSecretProtoP\x01Z4github.com/RomanAgaltsev/keyper/pkg/keyper/v1;keyper\xa2\x02\x03KXX\xaa\x02\tKeyper.V1\xca\x02\tKeyper\\V1\xe2\x02\x15Keyper\\V1\\GPBMetadata\xea\x02\n" +
	"Keyper::V1b\x06proto3"

var (
	file_keyper_v1_secret_proto_rawDescOnce sync.Once
	file_keyper_v1_secret_proto_rawDescData []byte
)

func file_keyper_v1_secret_proto_rawDescGZIP() []byte {
	file_keyper_v1_secret_proto_rawDescOnce.Do(func() {
		file_keyper_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyper_v1_secret_proto_rawDesc), len(file_keyper_v1_secret_proto_rawDesc)))
	})
	return file_keyper_v1_secret_proto_rawDescData
}

var file_keyper_v1_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keyper_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_keyper_v1_secret_proto_goTypes = []any{
	(SecretType)(0),                                   // 0: keyper.v1.SecretType
	(*Secret)(nil),                                    // 1: keyper.v1.Secret
	(*CreateSecretV1Request)(nil),                     // 2: keyper.v1.CreateSecretV1Request
	(*CreateSecretV1Response)(nil),                    // 3: keyper.v1.CreateSecretV1Response
	(*GetSecretV1Request)(nil),                        // 4: keyper.v1.GetSecretV1Request
	(*GetSecretV1Response)(nil),                       // 5: keyper.v1.GetSecretV1Response
	(*ListSecretsV1Response)(nil),                     // 6: keyper.v1.ListSecretsV1Response
	(*UpdateSecretV1Request)(nil),                     // 7: keyper.v1.UpdateSecretV1Request
	(*UpdateSecretV1Response)(nil),                    // 8: keyper.v1.UpdateSecretV1Response
	(*DeleteSecretV1Request)(nil),                     // 9: keyper.v1.DeleteSecretV1Request
	(*DeleteSecretV1Response)(nil),                    // 10: keyper.v1.DeleteSecretV1Response
	(*CreateSecretV1Response_CreateSecretResult)(nil), // 11: keyper.v1.CreateSecretV1Response.CreateSecretResult
	(*GetSecretV1Response_GetSecretResult)(nil),       // 12: keyper.v1.GetSecretV1Response.GetSecretResult
	(*UpdateSecretV1Response_UpdateSecretResult)(nil), // 13: keyper.v1.UpdateSecretV1Response.UpdateSecretResult
	(*DeleteSecretV1Response_DeleteSecretResult)(nil), // 14: keyper.v1.DeleteSecretV1Response.DeleteSecretResult
	(*timestamppb.Timestamp)(nil),                     // 15: google.protobuf.Timestamp
}
var file_keyper_v1_secret_proto_depIdxs = []int32{
	0,  // 0: keyper.v1.Secret.type:type_name -> keyper.v1.SecretType
	15, // 1: keyper.v1.Secret.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: keyper.v1.Secret.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: keyper.v1.CreateSecretV1Request.secret:type_name -> keyper.v1.Secret
	11, // 4: keyper.v1.CreateSecretV1Response.result:type_name -> keyper.v1.CreateSecretV1Response.CreateSecretResult
	12, // 5: keyper.v1.GetSecretV1Response.result:type_name -> keyper.v1.GetSecretV1Response.GetSecretResult
	1,  // 6: keyper.v1.ListSecretsV1Response.secret:type_name -> keyper.v1.Secret
	1,  // 7: keyper.v1.UpdateSecretV1Request.secret:type_name -> keyper.v1.Secret
	13, // 8: keyper.v1.UpdateSecretV1Response.result:type_name -> keyper.v1.UpdateSecretV1Response.UpdateSecretResult
	14, // 9: keyper.v1.DeleteSecretV1Response.result:type_name -> keyper.v1.DeleteSecretV1Response.DeleteSecretResult
	1,  // 10: keyper.v1.GetSecretV1Response.GetSecretResult.secret:type_name -> keyper.v1.Secret
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_keyper_v1_secret_proto_init() }
func file_keyper_v1_secret_proto_init() {
	if File_keyper_v1_secret_proto != nil {
		return
	}
	file_keyper_v1_secret_proto_msgTypes[0].OneofWrappers = []any{}
	file_keyper_v1_secret_proto_msgTypes[10].OneofWrappers = []any{}
	file_keyper_v1_secret_proto_msgTypes[11].OneofWrappers = []any{}
	file_keyper_v1_secret_proto_msgTypes[12].OneofWrappers = []any{}
	file_keyper_v1_secret_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyper_v1_secret_proto_rawDesc), len(file_keyper_v1_secret_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyper_v1_secret_proto_goTypes,
		DependencyIndexes: file_keyper_v1_secret_proto_depIdxs,
		EnumInfos:         file_keyper_v1_secret_proto_enumTypes,
		MessageInfos:      file_keyper_v1_secret_proto_msgTypes,
	}.Build()
	File_keyper_v1_secret_proto = out.File
	file_keyper_v1_secret_proto_goTypes = nil
	file_keyper_v1_secret_proto_depIdxs = nil
}
