// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: keyper/v1/user.proto

package keyper

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserCredentials contains credentials either for user registration or login.
type UserCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User login (email).
	// Identifies the user across the entire application.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// User encryption key.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredentials) Reset() {
	*x = UserCredentials{}
	mi := &file_keyper_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentials) ProtoMessage() {}

func (x *UserCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentials.ProtoReflect.Descriptor instead.
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserCredentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserCredentials) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// RegisterLoginResult contains result of either user registration or login.
type RegisterLoginResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security token.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLoginResult) Reset() {
	*x = RegisterLoginResult{}
	mi := &file_keyper_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLoginResult) ProtoMessage() {}

func (x *RegisterLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLoginResult.ProtoReflect.Descriptor instead.
func (*RegisterLoginResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterLoginResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RegisterUserV1Request contains credentials of user to register.
type RegisterUserV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New user credentials.
	Credentials   *UserCredentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserV1Request) Reset() {
	*x = RegisterUserV1Request{}
	mi := &file_keyper_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserV1Request) ProtoMessage() {}

func (x *RegisterUserV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserV1Request.ProtoReflect.Descriptor instead.
func (*RegisterUserV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserV1Request) GetCredentials() *UserCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// RegisterUserV1Response is received in response to a RegisterUserV1 rpc.
//
// It contains a security token for newly registered user.
type RegisterUserV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of new user registration.
	Result        *RegisterLoginResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserV1Response) Reset() {
	*x = RegisterUserV1Response{}
	mi := &file_keyper_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserV1Response) ProtoMessage() {}

func (x *RegisterUserV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserV1Response.ProtoReflect.Descriptor instead.
func (*RegisterUserV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserV1Response) GetResult() *RegisterLoginResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// LoginUserV1Request contains credentials of user to login.
type LoginUserV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existed user credentials.
	Credentials   *UserCredentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserV1Request) Reset() {
	*x = LoginUserV1Request{}
	mi := &file_keyper_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserV1Request) ProtoMessage() {}

func (x *LoginUserV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserV1Request.ProtoReflect.Descriptor instead.
func (*LoginUserV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserV1Request) GetCredentials() *UserCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// LoginUserV1Response is received in response to a LoginUserV1 rpc.
//
// It contains a security token for existed user.
type LoginUserV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of existed user login.
	Result        *RegisterLoginResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserV1Response) Reset() {
	*x = LoginUserV1Response{}
	mi := &file_keyper_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserV1Response) ProtoMessage() {}

func (x *LoginUserV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserV1Response.ProtoReflect.Descriptor instead.
func (*LoginUserV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginUserV1Response) GetResult() *RegisterLoginResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_keyper_v1_user_proto protoreflect.FileDescriptor

var file_keyper_v1_user_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0xba, 0x48, 0x07, 0xc8, 0x01, 0x01, 0x72, 0x02, 0x60, 0x01, 0x52, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0xba, 0x48, 0x07, 0xc8, 0x01, 0x01, 0x72, 0x02, 0x10, 0x01, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x33, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5d, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x44, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x58, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x5a, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x65, 0x79,
	0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x55, 0x0a, 0x13, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x95, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x65, 0x79, 0x70, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f,
	0x6d, 0x61, 0x6e, 0x41, 0x67, 0x61, 0x6c, 0x74, 0x73, 0x65, 0x76, 0x2f, 0x6b, 0x65, 0x79, 0x70,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x6b, 0x65, 0x79, 0x70, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x4b, 0x58, 0x58, 0xaa, 0x02, 0x09,
	0x4b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x4b, 0x65, 0x79, 0x70,
	0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x4b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a,
	0x4b, 0x65, 0x79, 0x70, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_keyper_v1_user_proto_rawDescOnce sync.Once
	file_keyper_v1_user_proto_rawDescData []byte
)

func file_keyper_v1_user_proto_rawDescGZIP() []byte {
	file_keyper_v1_user_proto_rawDescOnce.Do(func() {
		file_keyper_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyper_v1_user_proto_rawDesc), len(file_keyper_v1_user_proto_rawDesc)))
	})
	return file_keyper_v1_user_proto_rawDescData
}

var file_keyper_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_keyper_v1_user_proto_goTypes = []any{
	(*UserCredentials)(nil),        // 0: keyper.v1.UserCredentials
	(*RegisterLoginResult)(nil),    // 1: keyper.v1.RegisterLoginResult
	(*RegisterUserV1Request)(nil),  // 2: keyper.v1.RegisterUserV1Request
	(*RegisterUserV1Response)(nil), // 3: keyper.v1.RegisterUserV1Response
	(*LoginUserV1Request)(nil),     // 4: keyper.v1.LoginUserV1Request
	(*LoginUserV1Response)(nil),    // 5: keyper.v1.LoginUserV1Response
}
var file_keyper_v1_user_proto_depIdxs = []int32{
	0, // 0: keyper.v1.RegisterUserV1Request.credentials:type_name -> keyper.v1.UserCredentials
	1, // 1: keyper.v1.RegisterUserV1Response.result:type_name -> keyper.v1.RegisterLoginResult
	0, // 2: keyper.v1.LoginUserV1Request.credentials:type_name -> keyper.v1.UserCredentials
	1, // 3: keyper.v1.LoginUserV1Response.result:type_name -> keyper.v1.RegisterLoginResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_keyper_v1_user_proto_init() }
func file_keyper_v1_user_proto_init() {
	if File_keyper_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyper_v1_user_proto_rawDesc), len(file_keyper_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyper_v1_user_proto_goTypes,
		DependencyIndexes: file_keyper_v1_user_proto_depIdxs,
		MessageInfos:      file_keyper_v1_user_proto_msgTypes,
	}.Build()
	File_keyper_v1_user_proto = out.File
	file_keyper_v1_user_proto_goTypes = nil
	file_keyper_v1_user_proto_depIdxs = nil
}
