// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: keyper/v1/user.proto

package keyper

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserCredentials contains credentials either for user registration or login.
type UserCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User login (email).
	// Identifies the user across the entire application.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// User password.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// User identifier (uuid).
	Id            *string `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredentials) Reset() {
	*x = UserCredentials{}
	mi := &file_keyper_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentials) ProtoMessage() {}

func (x *UserCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentials.ProtoReflect.Descriptor instead.
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserCredentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCredentials) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// RegisterLoginResult contains result of either user registration or login.
type RegisterLoginResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Security token.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// User identifier (uuid).
	Id            *string `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLoginResult) Reset() {
	*x = RegisterLoginResult{}
	mi := &file_keyper_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLoginResult) ProtoMessage() {}

func (x *RegisterLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLoginResult.ProtoReflect.Descriptor instead.
func (*RegisterLoginResult) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterLoginResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterLoginResult) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// RegisterUserV1Request contains credentials of user to register.
type RegisterUserV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New user credentials.
	Credentials   *UserCredentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserV1Request) Reset() {
	*x = RegisterUserV1Request{}
	mi := &file_keyper_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserV1Request) ProtoMessage() {}

func (x *RegisterUserV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserV1Request.ProtoReflect.Descriptor instead.
func (*RegisterUserV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserV1Request) GetCredentials() *UserCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// RegisterUserV1Response is received in response to a RegisterUserV1 rpc.
//
// It contains a security token for newly registered user.
type RegisterUserV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of new user registration.
	Result        *RegisterLoginResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserV1Response) Reset() {
	*x = RegisterUserV1Response{}
	mi := &file_keyper_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserV1Response) ProtoMessage() {}

func (x *RegisterUserV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserV1Response.ProtoReflect.Descriptor instead.
func (*RegisterUserV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserV1Response) GetResult() *RegisterLoginResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// LoginUserV1Request contains credentials of user to login.
type LoginUserV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existed user credentials.
	Credentials   *UserCredentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserV1Request) Reset() {
	*x = LoginUserV1Request{}
	mi := &file_keyper_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserV1Request) ProtoMessage() {}

func (x *LoginUserV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserV1Request.ProtoReflect.Descriptor instead.
func (*LoginUserV1Request) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserV1Request) GetCredentials() *UserCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// LoginUserV1Response is received in response to a LoginUserV1 rpc.
//
// It contains a security token for existed user.
type LoginUserV1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of existed user login.
	Result        *RegisterLoginResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserV1Response) Reset() {
	*x = LoginUserV1Response{}
	mi := &file_keyper_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserV1Response) ProtoMessage() {}

func (x *LoginUserV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_keyper_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserV1Response.ProtoReflect.Descriptor instead.
func (*LoginUserV1Response) Descriptor() ([]byte, []int) {
	return file_keyper_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginUserV1Response) GetResult() *RegisterLoginResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_keyper_v1_user_proto protoreflect.FileDescriptor

const file_keyper_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14keyper/v1/user.proto\x12\tkeyper.v1\x1a\x1bbuf/validate/validate.proto\"\x81\x01\n" +
	"\x0fUserCredentials\x12 \n" +
	"\x05login\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05login\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\bpassword\x12\x1d\n" +
	"\x02id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"Y\n" +
	"\x13RegisterLoginResult\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05token\x12\x1d\n" +
	"\x02id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"]\n" +
	"\x15RegisterUserV1Request\x12D\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.keyper.v1.UserCredentialsB\x06\xbaH\x03\xc8\x01\x01R\vcredentials\"X\n" +
	"\x16RegisterUserV1Response\x12>\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.keyper.v1.RegisterLoginResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\"Z\n" +
	"\x12LoginUserV1Request\x12D\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.keyper.v1.UserCredentialsB\x06\xbaH\x03\xc8\x01\x01R\vcredentials\"U\n" +
	"\x13LoginUserV1Response\x12>\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.keyper.v1.RegisterLoginResultB\x06\xbaH\x03\xc8\x01\x01R\x06resultB\x95\x01\n" +
	"\rcom.keyper.v1B\tUserProtoP\x01Z4github.com/RomanAgaltsev/keyper/pkg/keyper/v1;keyper\xa2\x02\x03KXX\xaa\x02\tKeyper.V1\xca\x02\tKeyper\\V1\xe2\x02\x15Keyper\\V1\\GPBMetadata\xea\x02\n" +
	"Keyper::V1b\x06proto3"

var (
	file_keyper_v1_user_proto_rawDescOnce sync.Once
	file_keyper_v1_user_proto_rawDescData []byte
)

func file_keyper_v1_user_proto_rawDescGZIP() []byte {
	file_keyper_v1_user_proto_rawDescOnce.Do(func() {
		file_keyper_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyper_v1_user_proto_rawDesc), len(file_keyper_v1_user_proto_rawDesc)))
	})
	return file_keyper_v1_user_proto_rawDescData
}

var file_keyper_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_keyper_v1_user_proto_goTypes = []any{
	(*UserCredentials)(nil),        // 0: keyper.v1.UserCredentials
	(*RegisterLoginResult)(nil),    // 1: keyper.v1.RegisterLoginResult
	(*RegisterUserV1Request)(nil),  // 2: keyper.v1.RegisterUserV1Request
	(*RegisterUserV1Response)(nil), // 3: keyper.v1.RegisterUserV1Response
	(*LoginUserV1Request)(nil),     // 4: keyper.v1.LoginUserV1Request
	(*LoginUserV1Response)(nil),    // 5: keyper.v1.LoginUserV1Response
}
var file_keyper_v1_user_proto_depIdxs = []int32{
	0, // 0: keyper.v1.RegisterUserV1Request.credentials:type_name -> keyper.v1.UserCredentials
	1, // 1: keyper.v1.RegisterUserV1Response.result:type_name -> keyper.v1.RegisterLoginResult
	0, // 2: keyper.v1.LoginUserV1Request.credentials:type_name -> keyper.v1.UserCredentials
	1, // 3: keyper.v1.LoginUserV1Response.result:type_name -> keyper.v1.RegisterLoginResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_keyper_v1_user_proto_init() }
func file_keyper_v1_user_proto_init() {
	if File_keyper_v1_user_proto != nil {
		return
	}
	file_keyper_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_keyper_v1_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyper_v1_user_proto_rawDesc), len(file_keyper_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyper_v1_user_proto_goTypes,
		DependencyIndexes: file_keyper_v1_user_proto_depIdxs,
		MessageInfos:      file_keyper_v1_user_proto_msgTypes,
	}.Build()
	File_keyper_v1_user_proto = out.File
	file_keyper_v1_user_proto_goTypes = nil
	file_keyper_v1_user_proto_depIdxs = nil
}
